---
- name: Install PgBouncer
  ansible.builtin.import_tasks: install.yml

- name: Allow PgBouncer traffic through the host firewall
  ansible.builtin.import_tasks: firewall.yml

- name: Configure and start PgBouncer
  ansible.builtin.import_tasks: configure.yml
