---
postgres_superuser_password: "{{ vault_postgres_superuser_password }}"
postgres_replication_password: "{{ vault_postgres_replication_password }}"
etcd_cluster_token: "{{ vault_etcd_cluster_token }}"
postgres_rewind_password: "{{ vault_postgres_rewind_password }}"
pgbouncer_auth_password: "{{ vault_pgbouncer_auth_password }}"