---
- name: Install pgbouncer_exporter
  ansible.builtin.import_tasks: install.yml

- name: Allow pgbouncer_exporter traffic through the host firewall
  ansible.builtin.import_tasks: firewall.yml

- name: Configure and start pgbouncer_exporter
  ansible.builtin.import_tasks: configure.yml
