---
- name: Restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted

- name: Reload systemd and restart alertmanager
  ansible.builtin.systemd:
    daemon_reload: true
    name: alertmanager
    state: restarted
