---
- name: Install node_exporter
  ansible.builtin.import_tasks: install.yml

- name: Allow node_exporter traffic through the host firewall
  ansible.builtin.import_tasks: firewall.yml

- name: Configure and start node_exporter
  ansible.builtin.import_tasks: configure.yml
