---
- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted

- name: reload systemd and restart prometheus
  systemd:
    daemon_reload: true
    name: prometheus
    state: restarted