---
- name: Create /etc/etcd config directory
  ansible.builtin.file:
    path: /etc/etcd
    state: directory
    owner: etcd
    group: etcd
    mode: "0750"

- name: Deploy etcd.conf.yml
  ansible.builtin.template:
    src: etcd.conf.yml.j2
    dest: /etc/etcd/etcd.conf.yml
    owner: etcd
    group: etcd
    mode: "0640"
  notify: restart etcd

- name: Deploy etcd systemd unit
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: "0644"
  notify: reload systemd and restart etcd

- name: Enable and start etcd
  ansible.builtin.systemd:
    name: etcd
    daemon_reload: true
    enabled: true
    state: started
