---
- name: Deploy Prometheus datasource provisioning
  ansible.builtin.copy:
    src: datasource.yml
    dest: /etc/grafana/provisioning/datasources/prometheus.yml
    owner: root
    group: grafana
    mode: "0640"
  notify: restart grafana

- name: Enable and start Grafana
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true
    state: started
