---
- name: Restart pgbouncer_exporter
  ansible.builtin.systemd:
    name: pgbouncer_exporter
    state: restarted

- name: Reload systemd and restart pgbouncer_exporter
  ansible.builtin.systemd:
    daemon_reload: true
    name: pgbouncer_exporter
    state: restarted
