---
- name: Create pgBackRest config directory
  ansible.builtin.file:
    path: /etc/pgbackrest
    state: directory
    owner: postgres
    group: postgres
    mode: "0750"

- name: Deploy pgbackrest.conf
  ansible.builtin.template:
    src: pgbackrest.conf.j2
    dest: /etc/pgbackrest/pgbackrest.conf
    owner: postgres
    group: postgres
    mode: "0640"

- name: Create pgBackRest log directory
  ansible.builtin.file:
    path: /var/log/pgbackrest
    state: directory
    owner: postgres
    group: postgres
    mode: "0750"
