---
- name: Restart patroni
  ansible.builtin.systemd:
    name: patroni
    state: restarted

- name: Reload systemd and restart patroni
  ansible.builtin.systemd:
    daemon_reload: true
    name: patroni
    state: restarted
