---
- name: Deploy postgresql.conf
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: "{{ pgdata_dir }}/postgresql.conf"
    owner: postgres
    group: postgres
    mode: "0600"

- name: Deploy pg_hba.conf
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: "{{ pgdata_dir }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: "0600"

- name: Deploy custom systemd service
  ansible.builtin.template:
    src: postgresql.service.j2
    dest: /etc/systemd/system/pg18.service
    mode: "0644"
  notify: reload systemd

- name: Enable and start PostgreSQL
  ansible.builtin.systemd:
    name: pg18
    daemon_reload: true
    enabled: true
    state: started
