---
- name: Take a base backup from the primary (populates PGDATA and PGWAL, writes standby.signal)
  ansible.builtin.command: >
    /usr/lib/postgresql/18/bin/pg_basebackup
    --host={{ hostvars[groups['pg_primary'][0]]['private_ip'] }}
    --username=replicator
    --pgdata={{ pgdata_dir }}
    --waldir={{ pgwal_dir }}
    --format=plain
    --wal-method=stream
    --write-recovery-conf
    --checkpoint=fast
    --progress
  args:
    creates: "{{ pgdata_dir }}/PG_VERSION"
  become: true
  become_user: postgres
  environment:
    PGPASSWORD: "{{ postgres_replication_password }}"
  no_log: true
