---
- name: Create replication role on the primary
  ansible.builtin.command: >
    psql -c "CREATE ROLE replicator WITH REPLICATION LOGIN ENCRYPTED PASSWORD '{{ postgres_replication_password }}';"
  become: true
  become_user: postgres
  register: postgresql_create_role_result
  failed_when: postgresql_create_role_result.rc != 0 and 'already exists' not in postgresql_create_role_result.stderr
  changed_when: "'CREATE ROLE' in postgresql_create_role_result.stdout"
  no_log: true
